/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rajeewa.blockchainvotingsystem;

import com.formdev.flatlaf.FlatLightLaf;

/**
 *
 * @author Rajeewa Asmadala
 */
public class ComMenu extends javax.swing.JFrame {

    /**
     * Creates new form ComMenu
     */
    public ComMenu() {
        initComponents();
        setSize(900,580);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn_mancand = new javax.swing.JButton();
        btn_registeroff = new javax.swing.JButton();
        btn_manoff = new javax.swing.JButton();
        btn_registercand = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        btn_logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 50, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 150, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Presidential Election");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 47));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lkflag.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Election Commission of Sri Lanka ©");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sri Lanka");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 40));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Menu");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 47));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_mancand.setBackground(new java.awt.Color(61, 90, 128));
        btn_mancand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_mancand.setForeground(new java.awt.Color(255, 255, 255));
        btn_mancand.setText("Manage Candidates");
        btn_mancand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_mancand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mancandActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mancand, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 210, 40));

        btn_registeroff.setBackground(new java.awt.Color(61, 90, 128));
        btn_registeroff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_registeroff.setForeground(new java.awt.Color(255, 255, 255));
        btn_registeroff.setText("Register Election Official");
        btn_registeroff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_registeroff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registeroffActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registeroff, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 210, 40));

        btn_manoff.setBackground(new java.awt.Color(61, 90, 128));
        btn_manoff.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_manoff.setForeground(new java.awt.Color(255, 255, 255));
        btn_manoff.setText("Manage Election Officials");
        btn_manoff.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_manoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_manoffActionPerformed(evt);
            }
        });
        jPanel2.add(btn_manoff, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 210, 40));

        btn_registercand.setBackground(new java.awt.Color(61, 90, 128));
        btn_registercand.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_registercand.setForeground(new java.awt.Color(255, 255, 255));
        btn_registercand.setText("Register Candidate");
        btn_registercand.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_registercand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registercandActionPerformed(evt);
            }
        });
        jPanel2.add(btn_registercand, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 210, 40));

        btn_start.setBackground(new java.awt.Color(61, 90, 128));
        btn_start.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_start.setForeground(new java.awt.Color(255, 255, 255));
        btn_start.setText("Get Election Results");
        btn_start.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });
        jPanel2.add(btn_start, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 360, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slemblem.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 60, 70));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 340, 140, 10));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 140, 10));

        btn_logout.setBackground(new java.awt.Color(238, 108, 77));
        btn_logout.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("Logout");
        btn_logout.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        jPanel2.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 70, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 630, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registeroffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registeroffActionPerformed
                    ComRegOff ro = new ComRegOff();
                    ro.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_registeroffActionPerformed

    private void btn_manoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_manoffActionPerformed
                    ComManOff mo = new ComManOff();
                    mo.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_manoffActionPerformed

    private void btn_registercandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registercandActionPerformed
                    ComRegCand rc = new ComRegCand();
                    rc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_registercandActionPerformed

    private void btn_mancandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mancandActionPerformed
                    ComManCand mc = new ComManCand();
                    mc.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_mancandActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
                    ComResults cr = new ComResults();
                    cr.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_startActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
                    Login li = new Login();
                    li.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                   System.err.println( "Failed to initialize LaF" );
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_mancand;
    private javax.swing.JButton btn_manoff;
    private javax.swing.JButton btn_registercand;
    private javax.swing.JButton btn_registeroff;
    private javax.swing.JButton btn_start;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
