/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rajeewa.blockchainvotingsystem;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Rajeewa Asmadala
 */
public class ComManCand extends javax.swing.JFrame {
    Connection conn;
    PreparedStatement pst;
    String query;
    int candid = 0;
    Validate ve = new Validate();
    
    
    String[] columnNames = {"ID", "Name", "NIC"};
    DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0){
        public boolean isCellEditable(int row, int column) {
        return false;
        }
        };
    /**
     * Creates new form ComManCand
     */
    public ComManCand() {
        initComponents();
        setSize(900,580);
        setLocationRelativeTo(null);
        setResizable(false);
        
        try {
            
                conn = SqlConn.connect();
                
            } catch (Exception ex) {
                
                Logger.getLogger(ComRegOff.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        
        
        try {
            
        Statement st = conn.createStatement();
        ResultSet rs=st.executeQuery("SELECT * FROM candidates");

        while (rs.next()) {  

            String id = rs.getString("id");
            String name = rs.getString("name");
            String nic = rs.getString("nic");

    
            String[] data = { id, name, nic } ;

            tableModel.addRow(data);             
        }
        
         } catch (Exception e) {
             
        JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);  
        
        }
        tbl_cand.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_tp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_cand = new javax.swing.JTable();
        txt_filter = new javax.swing.JTextField();
        btn_delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_update = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rb_yes = new javax.swing.JRadioButton();
        rb_no = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 50, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 150, 20));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Manage Candidates");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 47));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Presidential Election");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 47));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lkflag.jpg"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 80));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Election Commission of Sri Lanka ©");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Sri Lanka");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel4.setText("E-Mail:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        jLabel5.setText("NIC Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, -1));

        jLabel6.setText("Eligible:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, -1, -1));
        jPanel2.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 240, -1));
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 240, -1));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 240, -1));
        jPanel2.add(txt_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 240, -1));

        tbl_cand.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_cand.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_candMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_cand);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 500, 160));

        txt_filter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_filterActionPerformed(evt);
            }
        });
        txt_filter.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_filterKeyReleased(evt);
            }
        });
        jPanel2.add(txt_filter, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 200, 30));

        btn_delete.setBackground(new java.awt.Color(238, 108, 77));
        btn_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("Delete");
        btn_delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel2.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 370, 170, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slemblem.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 60, 70));

        btn_update.setBackground(new java.awt.Color(61, 90, 128));
        btn_update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_update.setForeground(new java.awt.Color(255, 255, 255));
        btn_update.setText("Update");
        btn_update.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_update, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 170, 50));

        btn_back.setBackground(new java.awt.Color(61, 90, 128));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 70, 30));

        jLabel2.setText("Filter:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        jLabel8.setText("Telephone:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));

        rb_yes.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb_yes);
        rb_yes.setText("YES");
        jPanel2.add(rb_yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, -1, 30));

        rb_no.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rb_no);
        rb_no.setText("NO");
        jPanel2.add(rb_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 630, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_filterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_filterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_filterActionPerformed

    private void txt_filterKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_filterKeyReleased

        TableRowSorter<DefaultTableModel> tr = new  TableRowSorter<DefaultTableModel> (tableModel);
        tbl_cand.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(txt_filter.getText()));

    }//GEN-LAST:event_txt_filterKeyReleased

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
            
        if (!(candid==0)){
            int input = JOptionPane.showConfirmDialog(null, "Do you want to proceed?", "Select an Option...",
                                        JOptionPane.YES_NO_OPTION, JOptionPane.ERROR_MESSAGE);
            
            if(input==0){
                try {
                    String sql="DELETE FROM candidates WHERE id=?";
                    pst = conn.prepareStatement(sql);
                    pst.setInt(1, candid);
                    pst.execute();
                    
                    try {
            
                    Statement st = conn.createStatement();
                    ResultSet rs=st.executeQuery("SELECT * FROM candidates");

                    tableModel.setRowCount(0);

                    while (rs.next()) {  

                        String id = rs.getString("id");
                        String name = rs.getString("name");
                        String nic = rs.getString("nic");


                        String[] data = { id, name, nic } ;

                        tableModel.addRow(data);             
                    }

                     } catch (Exception e) {

                    JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);  

                    }
                    tbl_cand.setModel(tableModel);
                    
                    
                    
                } catch (SQLException ex) {
                    Logger.getLogger(ComManCand.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select record.");
        }
        
        
            
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        
        if(!(candid==0)){
            
            if(!("".equals(txt_name.getText()) || "".equals(txt_nic.getText()) || "".equals(txt_email.getText()) || "".equals(txt_tp.getText()))){
                
                if(!(txt_tp.getText().length() > 10)){
                    
                    if(ve.isValidEmailAddress(txt_email.getText())){
                        
                        try {
            
                                String sql="UPDATE candidates SET name=?,nic=?,email=?,telephone=?,eligibility=? WHERE id=?";
                                pst = conn.prepareStatement(sql);
                                pst.setString(1,txt_name.getText());
                                pst.setString(2,txt_nic.getText());
                                pst.setString(3,txt_email.getText());
                                pst.setString(4,txt_tp.getText());

                                boolean eligible;

                                if(rb_yes.isSelected()){
                                    eligible = true;
                                }else{
                                    eligible = false;
                                }

                                pst.setBoolean(5, eligible);
                                pst.setInt(6, candid);

                                pst.execute();

                                JOptionPane.showMessageDialog(null, "Successfully Updated!");

                                try {

                                Statement st = conn.createStatement();
                                ResultSet rs=st.executeQuery("SELECT * FROM candidates");

                                tableModel.setRowCount(0);

                                while (rs.next()) {  

                                    String id = rs.getString("id");
                                    String name = rs.getString("name");
                                    String nic = rs.getString("nic");


                                    String[] data = { id, name, nic } ;

                                    tableModel.addRow(data);             
                                }

                                 } catch (Exception e) {

                                JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);  

                                }
                                tbl_cand.setModel(tableModel);

                                }
                                catch (SQLException e)
                                {
                                    e.printStackTrace();
                                }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "Invalid email address.","Error!", JOptionPane.ERROR_MESSAGE);
                    }
                        
                }else{
                    JOptionPane.showMessageDialog(null, "Invalid telephone number.","Error!", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Cannot leave fields empty.","Error!", JOptionPane.ERROR_MESSAGE);
            }
            
             
        }else{
            JOptionPane.showMessageDialog(null, "Please select a candidate first.","Error!", JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btn_updateActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        ComMenu cm = new ComMenu();
        cm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void tbl_candMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_candMouseClicked
        DefaultTableModel model = (DefaultTableModel)tbl_cand.getModel();
        int selectedRowIndex = tbl_cand.getSelectedRow();
        
        candid = Integer.parseInt(model.getValueAt(selectedRowIndex, 0).toString());
        
        try {
            
            String query = ("SELECT * FROM candidates where id=?");
            pst = conn.prepareStatement(query);
            pst.setInt(1,candid);

            ResultSet rs = pst.executeQuery();

        while (rs.next()) {            
            txt_name.setText(rs.getString("name"));
            txt_nic.setText(rs.getString("nic"));
            txt_tp.setText(rs.getString("telephone"));
            txt_email.setText(rs.getString("email"));
            
            boolean eligible = rs.getBoolean("eligibility");
            
            if(eligible){
                rb_yes.setSelected(true);
            }else{
                rb_no.setSelected(true);
            }
            
                        
        }
        
         } catch (Exception e) {
             
        JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);  
        
        }
        
    }//GEN-LAST:event_tbl_candMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatLightLaf.setup();
        
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                   System.err.println( "Failed to initialize LaF" );
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComManCand().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rb_no;
    private javax.swing.JRadioButton rb_yes;
    private javax.swing.JTable tbl_cand;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_filter;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
