/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rajeewa.blockchainvotingsystem;

import com.formdev.flatlaf.FlatLightLaf;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Rajeewa Asmadala
 */
public class OffRegVoter extends javax.swing.JFrame {
        Connection conn;
        PreparedStatement pst;
        Validate ve = new Validate();
    /**
     * Creates new form OffRegVoter
     */
    public OffRegVoter() {
        initComponents();
        setSize(900,580);
        setLocationRelativeTo(null);
        setResizable(false);
        
        Date date = new Date();
        datechooser.setDate(date);
        
         try {
                conn = SqlConn.connect();
            } catch (Exception ex) {
                Logger.getLogger(ComRegOff.class.getName()).log(Level.SEVERE, null, ex);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_nic = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_tp = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cb_district = new javax.swing.JComboBox<>();
        datechooser = new com.toedter.calendar.JDateChooser();
        txt_add = new javax.swing.JTextField();
        btn_regvoter = new javax.swing.JButton();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(41, 50, 65));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 150, 20));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Register Voter");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 250, 47));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Presidential Election");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 250, 47));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lkflag.jpg"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 80));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Election Commission of Sri Lanka ©");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 250, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Sri Lanka");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 250, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 550));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));

        jLabel4.setText("E-Mail:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        jLabel5.setText("NIC Number:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, -1, -1));

        jLabel6.setText("Telephone:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));
        jPanel2.add(txt_nic, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 250, -1));
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 250, -1));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 250, -1));
        jPanel2.add(txt_tp, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 130, -1));

        jLabel7.setText("Address:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, -1, -1));

        jLabel8.setText("District:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jLabel9.setText("DOB:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, -1, -1));

        cb_district.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kandy", "Matale", "Nuwara Eliya", "Kegalle", "Ratnapura", "Trincomalee", "Batticaloa", "Ampara", "Badulla", "Monaragala", "Hambantota", "Matara", "Galle", "Anuradhapura", "Polonnaruwa", "Jaffna", "Kilinochchi", "Mannar", "Mullaitivu", "Vavuniya", "Puttalam", "Kurunegala", "Gampaha", "Colombo", "Kalutara" }));
        jPanel2.add(cb_district, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 250, -1));

        datechooser.setToolTipText("");
        datechooser.setDateFormatString("dd-MM-yyyy");
        jPanel2.add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 120, 20));
        jPanel2.add(txt_add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 250, -1));

        btn_regvoter.setBackground(new java.awt.Color(61, 90, 128));
        btn_regvoter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btn_regvoter.setForeground(new java.awt.Color(255, 255, 255));
        btn_regvoter.setText("Register");
        btn_regvoter.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_regvoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_regvoterActionPerformed(evt);
            }
        });
        jPanel2.add(btn_regvoter, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 200, 50));

        btn_back.setBackground(new java.awt.Color(61, 90, 128));
        btn_back.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        btn_back.setForeground(new java.awt.Color(255, 255, 255));
        btn_back.setText("Back");
        btn_back.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel2.add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, 70, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slemblem.jpg"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 60, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 0, 630, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_regvoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_regvoterActionPerformed
            
        
        if(!("".equals(txt_name.getText()) || "".equals(txt_nic.getText()) || "".equals(txt_email.getText()) || "".equals(txt_tp.getText()))){
                
                if(ve.isValidEmailAddress(txt_email.getText())){
                    
                    if(!(txt_tp.getText().length() > 10)){
                        
                        Random rnd = new Random();
                        int pin = rnd.nextInt(999999);

                        java.sql.Date date = new java.sql.Date(datechooser.getDate().getTime());      

                        try {

                        String sql="INSERT INTO voters (name,nic,email,telephone,address,district,dob,pin) VALUES (?,?,?,?,?,?,?,?)";
                        pst = conn.prepareStatement(sql);
                        pst.setString(1,txt_name.getText());
                        pst.setString(2,txt_nic.getText());
                        pst.setString(3,txt_email.getText());
                        pst.setString(4,txt_tp.getText());
                        pst.setString(5,txt_add.getText());
                        pst.setString(6,cb_district.getSelectedItem().toString());
                        pst.setDate(7,date);
                        pst.setInt(8,pin);
                        pst.execute();

                        JOptionPane.showMessageDialog(null, "Success");
                        }
                        catch (SQLException e)
                        {
                            e.printStackTrace();
                        }
                        
                                                
                    }else{
                        JOptionPane.showMessageDialog(null, "Invalid telephone number.","Error!", JOptionPane.ERROR_MESSAGE);
                    }
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Invalid email address.","Error!", JOptionPane.ERROR_MESSAGE);
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Cannot leave fields empty.","Error!", JOptionPane.ERROR_MESSAGE);
            }

    }//GEN-LAST:event_btn_regvoterActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        // TODO add your handling code here:
        OffMenu om = new OffMenu();
        om.setVisible(true);
        this.dispose();                 
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       FlatLightLaf.setup();
        
        try {
            javax.swing.UIManager.setLookAndFeel( new FlatLightLaf() );
            } catch( Exception ex ) {
                   System.err.println( "Failed to initialize LaF" );
            }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OffRegVoter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_regvoter;
    private javax.swing.JComboBox<String> cb_district;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_add;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nic;
    private javax.swing.JTextField txt_tp;
    // End of variables declaration//GEN-END:variables
}
